import 'branch_color_picker.dart';
import 'dart:io';
import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import '../Social/social_api.dart';
import '../Social/social_widgets.dart';
import 'branch_style.dart';

class BranchPdfOptions {
  BranchPdfOptions({
    required this.title,
    required this.subtitle,
    required this.footer,
    required this.columns,
  });
  String title, subtitle, footer, format = 'a4';
  bool landscape = true, includeDate = true;
  String headerColor = 'eff6ff', evenColor = 'ffffff', oddColor = 'f8fafc';
  final Set<String> columns;
}

Future<Uint8List> branchPdf(
  List<Json> rows,
  Map<String, String> labels,
  BranchPdfOptions options, {
  required bool rtl,
}) async {
  final font = pw.Font.ttf(
    await rootBundle.load('assets/fonts/vazir_fa/regular.ttf'),
  );
  final latin = pw.Font.ttf(
    await rootBundle.load('assets/fonts/iran_sansx_en/regular.ttf'),
  );
  final doc = pw.Document();
  final format = switch (options.format) {
    'letter' => PdfPageFormat.letter,
    'legal' => PdfPageFormat.legal,
    _ => PdfPageFormat.a4,
  };
  var keys = labels.keys.where(options.columns.contains).toList();
  if (rtl) keys = keys.reversed.toList();
  doc.addPage(
    pw.MultiPage(
      pageFormat: options.landscape ? format.landscape : format,
      margin: const pw.EdgeInsets.all(24),
      maxPages: 1000,
      theme: pw.ThemeData.withFont(
        base: font,
        bold: font,
        fontFallback: [latin],
      ),
      textDirection: rtl ? pw.TextDirection.rtl : pw.TextDirection.ltr,
      footer: (c) => pw.Column(
        children: [
          if (options.footer.isNotEmpty)
            pw.Text(options.footer, style: const pw.TextStyle(fontSize: 10)),
          pw.Text(
            '${c.pageNumber} / ${c.pagesCount}',
            style: const pw.TextStyle(fontSize: 10),
          ),
        ],
      ),
      build: (_) => [
        pw.Text(
          options.title,
          style: pw.TextStyle(fontSize: 22, fontWeight: pw.FontWeight.bold),
        ),
        pw.SizedBox(height: 6),
        pw.Text(options.subtitle),
        if (options.includeDate)
          pw.Text(
            DateTime.now().toLocal().toString().split('.').first,
            style: const pw.TextStyle(fontSize: 10),
          ),
        pw.SizedBox(height: 16),
        pw.TableHelper.fromTextArray(
          headers: [for (final k in keys) labels[k]!],
          data: [
            for (final row in rows) [for (final k in keys) '${row[k] ?? ''}'],
          ],
          headerDecoration: pw.BoxDecoration(
            color: PdfColor.fromHex(options.headerColor),
          ),
          rowDecoration: pw.BoxDecoration(
            color: PdfColor.fromHex(options.evenColor),
          ),
          oddRowDecoration: pw.BoxDecoration(
            color: PdfColor.fromHex(options.oddColor),
          ),
          border: null,
          cellAlignment: rtl
              ? pw.Alignment.centerRight
              : pw.Alignment.centerLeft,
          cellPadding: const pw.EdgeInsets.all(8),
          cellStyle: const pw.TextStyle(fontSize: 10),
          headerStyle: pw.TextStyle(
            fontSize: 10,
            fontWeight: pw.FontWeight.bold,
          ),
        ),
      ],
    ),
  );
  return doc.save();
}

Future<void> exportBranchesPdf(
  BuildContext context,
  List<Json> rows,
  Map<String, String> labels, {
  String? title,
  String? subtitle,
  String fileName = 'branches.pdf',
}) async {
  final rtl = Directionality.of(context) == TextDirection.rtl;
  String t(String fa, String en) => socialText(context, fa, en);
  final options = BranchPdfOptions(
    title: title ?? t('گزارش شعبه‌های آموزشگاه', 'Academy branches report'),
    subtitle:
        subtitle ??
        t('فهرست شعبه‌ها و اطلاعات پایه', 'Branches and basic information'),
    footer: t(
      'تولید شده توسط سیستم مدیریت آموزشگاه',
      'Generated by the academy management system',
    ),
    columns: labels.keys.toSet(),
  );
  final form = GlobalKey<FormState>();
  final approved = await showDialog<bool>(
    context: context,
    builder: (c) => Theme(
      data: branchTheme(context),
      child: StatefulBuilder(
        builder: (c, change) {
          Widget field(
            String label,
            String value,
            ValueChanged<String> update, {
            bool color = false,
          }) => Padding(
            padding: const EdgeInsets.only(bottom: 16),
            child: TextFormField(
              initialValue: value,
              decoration: InputDecoration(labelText: label),
              onChanged: update,
              validator: color
                  ? (v) => RegExp(r'^[0-9a-fA-F]{6}$').hasMatch(v ?? '')
                        ? null
                        : t(
                            'کد رنگ شش‌رقمی وارد کنید.',
                            'Enter a six-digit hex color.',
                          )
                  : null,
            ),
          );
          return BranchDialog(
            title: t('تنظیمات خروجی PDF', 'PDF export options'),
            child: Form(
              key: form,
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.stretch,
                children: [
                  field(
                    t('عنوان گزارش', 'Report title'),
                    options.title,
                    (v) => options.title = v,
                  ),
                  field(
                    t('زیرعنوان', 'Subtitle'),
                    options.subtitle,
                    (v) => options.subtitle = v,
                  ),
                  DropdownButtonFormField<String>(
                    initialValue: options.format,
                    decoration: InputDecoration(
                      labelText: t('فرمت صفحه', 'Page format'),
                    ),
                    items: [
                      for (final f in ['a4', 'letter', 'legal'])
                        DropdownMenuItem(
                          value: f,
                          child: Text(f.toUpperCase()),
                        ),
                    ],
                    onChanged: (v) => options.format = v!,
                  ),
                  const SizedBox(height: 16),
                  DropdownButtonFormField<bool>(
                    initialValue: options.landscape,
                    decoration: InputDecoration(
                      labelText: t('جهت صفحه', 'Orientation'),
                    ),
                    items: [
                      DropdownMenuItem(
                        value: true,
                        child: Text(t('افقی', 'Landscape')),
                      ),
                      DropdownMenuItem(
                        value: false,
                        child: Text(t('عمودی', 'Portrait')),
                      ),
                    ],
                    onChanged: (v) => options.landscape = v!,
                  ),
                  const SizedBox(height: 16),
                  field(
                    t('یادداشت پایین صفحه', 'Footer'),
                    options.footer,
                    (v) => options.footer = v,
                  ),
                  Text(t('ستون‌های خروجی PDF', 'PDF columns')),
                  for (final e in labels.entries)
                    CheckboxListTile(
                      contentPadding: EdgeInsets.zero,
                      title: Text(e.value),
                      value: options.columns.contains(e.key),
                      onChanged: (v) => change(() {
                        if (v == true) {
                          options.columns.add(e.key);
                        } else {
                          options.columns.remove(e.key);
                        }
                      }),
                    ),
                  const SizedBox(height: 16),
                  BranchColorPicker(
                    label: t('رنگ سطر عنوان', 'Header color'),
                    value: options.headerColor,
                    onChanged: (v) => options.headerColor = v,
                  ),
                  BranchColorPicker(
                    label: t('رنگ سطرهای زوج', 'Even row color'),
                    value: options.evenColor,
                    onChanged: (v) => options.evenColor = v,
                  ),
                  BranchColorPicker(
                    label: t('رنگ سطرهای فرد', 'Odd row color'),
                    value: options.oddColor,
                    onChanged: (v) => options.oddColor = v,
                  ),
                  CheckboxListTile(
                    contentPadding: EdgeInsets.zero,
                    title: Text(
                      t(
                        'نمایش تاریخ استخراج در بالای گزارش',
                        'Include export date',
                      ),
                    ),
                    value: options.includeDate,
                    onChanged: (v) => change(() => options.includeDate = v!),
                  ),
                  FilledButton(
                    onPressed: options.columns.isEmpty
                        ? null
                        : () {
                            if (form.currentState!.validate())
                              Navigator.pop(c, true);
                          },
                    child: Text(t('ایجاد PDF', 'Create PDF')),
                  ),
                ],
              ),
            ),
          );
        },
      ),
    ),
  );
  if (approved != true) return;
  final bytes = await branchPdf(rows, labels, options, rtl: rtl);
  final path = await FilePicker.platform.saveFile(
    fileName: fileName,
    bytes: bytes,
  );
  if (path != null &&
      (Platform.isWindows || Platform.isLinux || Platform.isMacOS))
    await File(path).writeAsBytes(bytes);
}
